######################################################################
# Automatically generated by qmake (3.0) Sun Aug 3 21:39:48 2014
######################################################################

QT += core gui widgets

TEMPLATE = app
TARGET = Unturned_Editor
INCLUDEPATH += . headers

# Input
HEADERS += headers/encoder.h headers/mainwindow.h
FORMS += encoder.ui mainwindow.ui
SOURCES += sources/encoder.cpp sources/main.cpp sources/mainwindow.cpp
